### ISSUE TITLE
How to implement swipeable segments in ionic 3?

### ISSUE THREAD

**Issue by binita12345** [siddhartha-gupta/ionic-3-swipe-able-segments#3]
I have to implement swipeable segments in ionic 3 application.

I am using https://github.com/siddhartha-gupta/ionic-3-swipe-able-segments/tree/develop/src/pages directives but i am getting following error:

    <ion-content padding>
     <div [ngSwitch]="category" swipeSegment [tabsList]="categories" 
      [ERROR ->][(currentTab)]="category" 
      (tabChanged)="onTabChanged($event)" class="swipe-area">
     <ion-list *ngSw"): 
     ng:///InvitefriendPageModule/InvitefriendPage.html@60:66
     Error: Template parse errors:
    Can't bind to 'tabsList' since it isn't a known property of 'div'. ("

    <ion-content padding>
     <div [ngSwitch]="category" swipeSegment [ERROR ->] . 
      [tabsList]="categories" [(currentTab)]="category" 
      (tabChanged)="onTabChanged($event)" class="swipe-ar"): 
       ng:///InvitefriendPageModule/InvitefriendPage.html@60:42
      Can't bind to 'currentTab' since it isn't a known property of 'div'. 
("

        <ion-content padding>
<div [ngSwitch]="category" swipeSegment [tabsList]="categories" [ERROR 
->][(currentTab)]="category" (tabChanged)="onTabChanged($event)" 
class="swipe-area">
<ion-list *ngSw"): 
ng:///InvitefriendPageModule/InvitefriendPage.html@60:66
at syntaxError (http://localhost:8100/build/vendor.js:80051:34)
at TemplateParser.parse 
(http://localhost:8100/build/vendor.js:104239:19)
at JitCompiler._parseTemplate 
(http://localhost:8100/build/vendor.js:114194:37)
at JitCompiler._compileTemplate 
(http://localhost:8100/build/vendor.js:114169:23)
at http://localhost:8100/build/vendor.js:114070:62
at Set.forEach (<anonymous>)
at JitCompiler._compileComponents 
(http://localhost:8100/build/vendor.js:114070:19)
at http://localhost:8100/build/vendor.js:113940:19
at Object.then (http://localhost:8100/build/vendor.js:80040:77)
at JitCompiler._compileModuleAndComponents 
(http://localhost:8100/build/vendor.js:113939:26)
at c (http://localhost:8100/build/polyfills.js:3:19752)
at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
at NavControllerBase._fireError 
(http://localhost:8100/build/vendor.js:51781:16)
at NavControllerBase._failed 
(http://localhost:8100/build/vendor.js:51774:14)
at http://localhost:8100/build/vendor.js:51821:59
at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
at Object.onInvoke (http://localhost:8100/build/vendor.js:5134:33)
at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
at r.run (http://localhost:8100/build/polyfills.js:3:10143)
at http://localhost:8100/build/polyfills.js:3:20242
My code is:

In app.module.ts:

     import { SwipeSegmentDirective } from '../directives/swipe- segment.directive';

     @NgModule({
     declarations: [
       MyApp,
       SwipeSegmentDirective
       // ProgressBarComponent
     ],

In invitefriend.ts:

    export class InvitefriendPage {

     public category: string = 'everyone';
     public categories: Array<string> = ['everyone', 'group', 'contact', 
     'directory']

     // tab1Root: any = "EveryonePage";
     // tab2Root: any = "GroupPage";
    // tab3Root: any = "ContactPage";
    // tab4Root: any = "DirectoryPage";
    // public categories: Array<string> = ['everyone', 'group', 'contact', 
    'directory']

     constructor(public navCtrl: NavController, public navParams: 
      NavParams) {
     }

     ionViewDidLoad() {
      console.log('ionViewDidLoad InvitefriendPage');
     }

     onTabChanged(tabName) {
      this.category = tabName;
     }

In invitefriend.html:

     <ion-header>
      <ion-navbar color="danger">   
       <ion-grid>
        <ion-row>
         <ion-col col-2 col-xl-2 class="wholeCol">
          <img src="assets/imgs/iconRn.png" class="iconHeader" item-start>
         </ion-col>
         <ion-col col-9 col-xl-9>
          <ion-grid class="search-css">
           <ion-row>
            <ion-col col-2 col-xl-2 class="search-div">
             <img src="assets/imgs/search.png" class="img-css">
            </ion-col>
            <ion-col col-10 col-xl-10>
              <ion-input type="text" (ionInput)="getItems($event)" 
                [(ngModel)]="searchTerm" class="inputSearch" 
                 placeholder="Search by name"></ion-input>
               </ion-col>
              </ion-row>
             </ion-grid>

            </ion-col>
            <ion-col col-1 col-xl-1 class="colSetting">
             <img src="assets/imgs/close.png" class="iconclose" 
                (click)="closePage()">
             </ion-col>
            </ion-row>
           </ion-grid>

    <ion-toolbar class="toolbar-color myToolbar">
     <ion-segment [(ngModel)]="category" class="tabsSeg">

      <ion-segment-button value="everyone" class="segBtn tabname 
        active activated">
         Everyone
      </ion-segment-button>
      <ion-segment-button value="group" class="segBtn tabname">
        Group
      </ion-segment-button>
      <ion-segment-button value="contact" class="segBtn tabname">
        Contact
      </ion-segment-button>
      <ion-segment-button value="directory" class="segBtn tabname">
        Directory
      </ion-segment-button>
    </ion-segment>
   </ion-toolbar>
  </ion-navbar>

 </ion-header> 

     <ion-content padding>
       <div [ngSwitch]="category" swipeSegment [tabsList]="categories" 
        [(currentTab)]="category" (tabChanged)="onTabChanged($event)" 
         class="swipe-area">
       <ion-list *ngSwitchCase="'everyone'">
        <ion-item>
          Batman Begins
         </ion-item>
          <ion-item>
          Transporter
         </ion-item>
         <ion-item>
          Million Dollar Baby
          </ion-item>
         </ion-list>

         <ion-list *ngSwitchCase="'group'">
          <ion-item>
            Game of Thrones
          </ion-item>
          <ion-item>
            Daredevil
           </ion-item>
           <ion-item>
            Arrow
           </ion-item>
         </ion-list>

        <ion-list *ngSwitchCase="'contact'">
         <ion-item>
           Ice Age
         </ion-item>
          <ion-item>
          Lion King
          </ion-item>
          <ion-item>
             Up
         </ion-item>
         </ion-list>

          <ion-list *ngSwitchCase="'directory'">
         <ion-item>
          Ice Age1
           </ion-item>
           <ion-item>
           Lion King1
          </ion-item>
           <ion-item>
            Up1
         </ion-item>
        </ion-list>
       </div>
      </ion-content>

I need any solution to solve above error, please give here solution as soon as possible, it would be really appreciated.

**Comment by siddhartha-gupta** [comment]
Hey, apologies for replying after such a long delay. If you are still facing an issue, can you share a dummy application with me, as it'll be easier for me to do RCA

**Comment by jonathanferreyra** [comment]
Hi! I'm getting exactly the same error. 

`Can't bind to 'currentTab' since it isn't a known property of 'div'`

there is a way to fix this? thanks

**Comment by siddhimandodi** [comment]
![screenshot 2019-02-04 at 3 49 25 pm](https://user-images.githubusercontent.com/47318571/52202479-8bf6f800-2894-11e9-8280-c2d4fc2a5ee1.png)

please help

**Comment by siddhartha-gupta** [comment]
@jonathanferreyra @siddhimandod please share a dummy app/code via github/stackblitz, it'll be easier to debug
